name: widgets
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0-180.3.beta <4.0.0"  # Adjusted SDK version to match the beta version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Updated version
  rename_app: ^1.6.1
  flutter_launcher_icons: ^0.14.1
  animated_splash_screen: ^1.3.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  animated_notch_bottom_bar: ^1.0.3
  image_picker: ^1.1.2
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  flutter_colorpicker: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/app_icon.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Updated version

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/png/navbar/
    - assets/png/technologies/
