// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgTzv_rHtq4ZNSDgAljLO0VRqT1Ix6hdk',
    appId: '1:162533794915:web:3f92f481197e77a8780456',
    messagingSenderId: '162533794915',
    projectId: 'widgets-d6cb9',
    authDomain: 'widgets-d6cb9.firebaseapp.com',
    storageBucket: 'widgets-d6cb9.appspot.com',
    measurementId: 'G-GMZ6RT00S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3ft1vKmRVxHRaIJjfuWO02BOM7ulRUIg',
    appId: '1:162533794915:android:2dd92f3b89b42383780456',
    messagingSenderId: '162533794915',
    projectId: 'widgets-d6cb9',
    storageBucket: 'widgets-d6cb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGhSS48ZWeIuIHhEf2gQSHtLhc3qj-bKA',
    appId: '1:162533794915:ios:f9c2f904a47e3c0b780456',
    messagingSenderId: '162533794915',
    projectId: 'widgets-d6cb9',
    storageBucket: 'widgets-d6cb9.appspot.com',
    iosBundleId: 'com.example.widgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGhSS48ZWeIuIHhEf2gQSHtLhc3qj-bKA',
    appId: '1:162533794915:ios:f9c2f904a47e3c0b780456',
    messagingSenderId: '162533794915',
    projectId: 'widgets-d6cb9',
    storageBucket: 'widgets-d6cb9.appspot.com',
    iosBundleId: 'com.example.widgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgTzv_rHtq4ZNSDgAljLO0VRqT1Ix6hdk',
    appId: '1:162533794915:web:e76e0c8c7d5e2ad0780456',
    messagingSenderId: '162533794915',
    projectId: 'widgets-d6cb9',
    authDomain: 'widgets-d6cb9.firebaseapp.com',
    storageBucket: 'widgets-d6cb9.appspot.com',
    measurementId: 'G-YP0RXEBB14',
  );
}
